services:
  webui:
    image: ghcr.io/open-webui/open-webui:v0.9.2-cuda
    environment:
      ENABLE_OLLAMA_API: true
      OLLAMA_BASE_URL: http://localhost:11434
      WEBUI_AUTH: false
      ENABLE_OPENAI_API: true
      OPENAI_API_BASE_URL: http://litellm:4000
      OPENAI_API_KEY: ${GENERIC_API_KEY}
      ENABLE_OTEL: true
      OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
      ENABLE_PERSISTENT_CONFIG: false
      ENABLE_DIRECT_CONNECTIONS: true
    volumes:
      - webui_data:/app/backend/data
    networks:
      - main
    # depends_on:
    #   - ollama

  webui-pipelines:
    image: ghcr.io/open-webui/pipelines:main
    volumes:
      - ../pipelines:/app/pipelines
    networks:
      - main
    environment:
      LANGFUSE_HOST: http://langfuse:3000
    depends_on:
      - webui

  mcpo:
    image: ghcr.io/open-webui/mcpo:main
    # volumes:
    #   - ../mcp.json:/app/mcp.json
    command:
      - "--config=/app/mcp.json"
    networks:
      - main
    depends_on:
      - webui

volumes:
  webui_data:
